### ISSUE TITLE
domains exception

### ISSUE THREAD

**Issue by rocx1900** [CrowdStrike/sccmhound#1]
sccm infra with 1 primary server , multiple domains 
collection errors out with this message

Resolving domains triggered an exception.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SCCMHound.src.DomainsResolver..ctor(List`1 users, List`1 computers, List`1 groups)
   at SCCMHound.SCCMHound.invoke(String sccmServer, String sccmSiteCode, Boolean loop, T

**Comment by matcluck-cs** [comment]
Hi @rocx1900, thank you for submitting the issue! I'd say what is happening is that an object doesn't have one of the required attributes required to perform domain resolution.

I've created a new branch with additional exception handling to prevent KeyNotFoundExceptions thrown in DomainsResolver from causing the application to crash.

Could you please test and let me know if this resolves your issue?

https://github.com/CrowdStrike/sccmhound/tree/bugfix/domains-exception
[SCCMHound-DomainsExceptionBugfix.exe.zip](https://github.com/user-attachments/files/18287695/SCCMHound-DomainsExceptionBugfix.exe.zip)

Cheers!

**Comment by rocx1900** [comment]
it worked fine this time.
thank you for the help

**Comment by matcluck-cs** [comment]
@rocx1900, thank you for the feedback. Please let me know if you run into any more issues or have any questions, happy to help. Cheers!
